alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias apt-get='sudo apt-get'
alias bc='bc -l'
alias chmodx='chmod +x'
alias codesu='sudo code --user-data-dir jeffp2662'
alias cpuinfo='lscpu'
alias dcc='sudo docker container'
alias dci='sudo docker image'
alias dcv='sudo docker volume'
alias dns-current='systemd-resolve --status | grep "Current DNS Server" | head -1'
alias dns-status='systemd-resolve --status'
alias docker='sudo docker'
alias egrep='egrep --color=always'
alias fgrep='fgrep --color=always'
alias find='sudo find'
alias findfast='find / (-path /mnt -o -path /media) -prune -o'
alias gp='globalprotect'
alias gpconnect='globalprotect connect --portal passport.sa.ucsb.edu --username "sa\pignataro-j"'
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
alias grep='grep --color=always'
alias halt='sudo /sbin/halt'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -lahF --color=always'
alias meminfo='free -m -l -t'
alias pip='python3 -m pip'
alias poweroff='sudo /sbin/poweroff'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias py='python3'
alias reboot='sudo /sbin/reboot'
alias restart='sudo /sbin/shutdown -r now'
alias rsyncarchive='sudo rsync --archive --verbose --progress'
alias shutdown='sudo /sbin/shutdown'
alias startdocker='sh /usr/local/sbin/start_docker.sh'
alias terminus='/$HOME/vendor/bin/terminus'
alias terminusauth='/$HOME/vendor/bin/terminus auth:login --email=jeffp2662@ucsb.edu'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias updatey='sudo apt-get --yes'
alias wget='wget -c'
